# Generated by Django 5.0.6 on 2024-06-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_review_company_review_businessprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
